-- MySQL Script generated by MySQL Workbench
-- Fri Aug 23 19:12:23 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema infinity_cloud
-- -----------------------------------------------------
-- Gestion de infinity cloud

-- -----------------------------------------------------
-- Schema infinity_cloud
--
-- Gestion de infinity cloud
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `infinity_cloud` DEFAULT CHARACTER SET utf8 ;
USE `infinity_cloud` ;

-- -----------------------------------------------------
-- Table `infinity_cloud`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infinity_cloud`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(70) NULL,
  `user_name` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  `statut` INT NULL DEFAULT 0,
  `phone_number` VARCHAR(45) NULL,
  `creation_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `update_date` DATETIME NULL,
  `token` VARCHAR(80) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infinity_cloud`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infinity_cloud`.`log` (
  `log_id` INT NOT NULL AUTO_INCREMENT,
  `users` INT NOT NULL,
  `connect_date` DATE NULL,
  `ip` VARCHAR(45) NULL,
  `connect_hour` TIME NULL,
  PRIMARY KEY (`log_id`, `users`),
  INDEX `fk_log_users_idx` (`users` ASC),
  CONSTRAINT `fk_log_users`
    FOREIGN KEY (`users`)
    REFERENCES `infinity_cloud`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infinity_cloud`.`subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infinity_cloud`.`subscription` (
  `id_subscription` INT NOT NULL AUTO_INCREMENT,
  `cost` FLOAT NULL,
  `storage` INT NULL,
  `name_subscription` VARCHAR(45) NULL,
  PRIMARY KEY (`id_subscription`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infinity_cloud`.`bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infinity_cloud`.`bill` (
  `bill_id` INT NOT NULL AUTO_INCREMENT,
  `users` INT NOT NULL,
  `bill_date` DATETIME NULL DEFAULT current_timestamp,
  `name_cloudPackage` VARCHAR(45) NULL,
  `storage_cloudPackage` INT NULL,
  `cost_cloudPackage` FLOAT NULL,
  PRIMARY KEY (`bill_id`, `users`),
  INDEX `fk_bill_users1_idx` (`users` ASC),
  CONSTRAINT `fk_bill_users1`
    FOREIGN KEY (`users`)
    REFERENCES `infinity_cloud`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
